### ISSUE TITLE
pycryptodome support in py-evm's p2p module

### ISSUE THREAD

**Issue by carver** [ethereum/eth-hash#12]
## What was wrong?

The `p2p` module of py-evm requires the ability to copy hashes that are incrementally calculated, as I understand this comment: https://github.com/ethereum/eth-hash/pull/11/files#r174900879

The current best solution is to use pysha3, which prevents pypy3 support in `p2p`.

## How can it be fixed?

Look for alternatives that allow `pycryptodome` to support `p2p`. Maybe it means digging further into pycryptodome internals, or working around the need for copying partially-computed incremental hashes.

**Comment by gsalgado** [comment]
ISTM that `p2p` only requires incremental hashing, which is possible using pycryptodome -- it just requires one to pass `update_after_digest=True` to `keccak.new()`

**Comment by pipermerriam** [comment]
@gsalgado I originally thought it was core `p2p` code but in-fact only `tests/p2p/peer_helpers.py` uses the `copy()` API so I think that we can just remove the `copy()` API usage which makes implementing this pretty easy.

**Comment by gsalgado** [comment]
https://github.com/ethereum/py-evm/pull/489

**Comment by carver** [comment]
This looks resolved on the py-evm side.
