### ISSUE TITLE
Consider dropping type checks in Keccak256 methods

### ISSUE THREAD

**Issue by gsalgado** [ethereum/eth-hash#16]
The `__call__()` and `new()` methods there will check the type of their arguments using `isinstance`, and although that should be a cheap check, these are code paths where performance is paramount given the number of times they are called when we perform trie operations on a fully synced DB. For example, when doing a full sync around 10% of the time is being spent into isinstance calls. Even though they're probably not all originating from these checks, I think we should consider removing them as these two methods have type annotations that should make it clear enough what is wrong in case they crash when passed an argument of the wrong type

**Comment by pipermerriam** [comment]
@gsalgado I'm betting most of those `isinstance` checks are happening in the validation code within the EVM thats checking things like this.:

- https://github.com/ethereum/py-evm/blob/master/evm/vm/memory.py#L45-L49
- https://github.com/ethereum/py-evm/blob/master/evm/vm/gas_meter.py#L27
- https://github.com/ethereum/py-evm/blob/master/evm/vm/stack.py#L38

**Comment by gsalgado** [comment]
The biggest offenders are actually rlp and trie: rlp/codec.py:72(encode_raw), trie/validation.py:11(validate_is_bytes), rlp/sedes/serializable.py:300(make_immutable). Just those 3 seem to account to almost half of all `isinstance()` calls

**Comment by pipermerriam** [comment]
Hrm, I could get onboard with dropping the check from `trie`.  It's not clear to me how to drop the check from `rlp` but we do call `make_immutable` on every argument during object instantiation.  It'd be nice to drop this but I *like* that when you pass a list into an rlp object it gets cast to a tuple.

**Comment by davesque** [comment]
I wonder if the behavior of some of those checks could be duplicated by appropriately coded try/except blocks.  According to the docs, try/except is very efficient when an exception is not raised: https://docs.python.org/3.6/faq/design.html#how-fast-are-exceptions.

**Comment by pipermerriam** [comment]
not the right solution **but** I did have a look at `functools.singledispatch` as a potential remedy for this but it's about 4x slower than a manual `isinstance` check (but way more elegant)

**Comment by carver** [comment]
>  rlp/codec.py:72(encode_raw)
> trie/validation.py:11(validate_is_bytes)
> rlp/sedes/serializable.py:300(make_immutable)

I think we can improve performance on all of these with `assert` statements. That way, default usages (and our tests) will work slower & safer, but we can disable asserts when running trinity client.

> trie/validation.py:11(validate_is_bytes)

Trivial to move to `asserts`

> rlp/sedes/serializable.py:300(make_immutable)

Not sure about this one. Can we simply *disallow* list as a valid input type, and use `assert` statements to reject lists?

>  rlp/codec.py:72(encode_raw)

This one is tougher, but here is one way to reduce the calls of `isinstance` by 2/3rds:

_old code_

```py
    if isinstance(item, Atomic):
        if len(item) == 1 and item[0] < 128:
            return item
        payload = item
        prefix_offset = 128  # string
    elif not isinstance(item, str) and isinstance(item, collections.Sequence):
        payload = b''.join(encode_raw(x) for x in item)
        prefix_offset = 192  # list
    else:
        msg = 'Cannot encode object of type {0}'.format(type(item).__name__)
        raise EncodingError(msg, item)
```

_new code_

```py
    if isinstance(item, Atomic):
        if len(item) == 1 and item[0] < 128:
            return item
        payload = item
        prefix_offset = 128  # string
    else:
        try:
            assert not isinstance(item, str)
        except AssertionError as exc:
            raise encoding_error(item) from exc

        try:
            payload = b''.join(encode_raw(x) for x in item)
        except TypeError as exc:
            raise encoding_error(item) from exc

        prefix_offset = 192  # list

def encoding_error(item)
        msg = 'Cannot encode object of type {0}'.format(type(item).__name__)
        return EncodingError(msg, item)
```

**Comment by carver** [comment]
I guess this should really be moved to py-evm/pyrlp/py-trie -- seems like we shouldn't remove the type checks in eth-hash until they are clearly a bottleneck.

**Comment by pipermerriam** [comment]
We can vendor the `encode_raw` implementation into py-trie.  That's an easy optimization, allowing us to drop checks without any compromise to the actual `rlp` library.  Bonus is that if we go ahead and vendor the `decode` as well we can drop the `rlp` dependency.

**Comment by davesque** [comment]
I've always felt weird about disabling asserts since some people incorrectly use them as a general exception throwing mechanism.  Thoughts on that?

**Comment by carver** [comment]
I hope that having libraries break when you turn off assertions would be very rare. I would certainly consider that broken. Is that something you've run into before? @davesque

**Comment by davesque** [comment]
@carver Actually, no thankfully.  And I guess it's probably not a very big risk and we'd notice it pretty quickly if a library broke in optimized mode.  But it does seems a bit undesirable that one should have to use `-O` to get decent performance.  I've never run across a library or tool where that was the case.  Maybe I've just never had occasion to use one that worked that way.

Is it possible that some of that manual type checking could just be removed altogether since a wrong value type would lead pretty quickly to a fairly obvious error?  It just feels a bit like we might be trying to shoehorn the wrong concerns into a dynamically typed language.

**Comment by pipermerriam** [comment]
eurika! (maybe)

We *should* be able to get *roughly* the same level of confidence with type checking via `mypy`.

**Comment by davesque** [comment]
@pipermerriam Yes, I agree with that.  Even if third party users of our libraries didn't use mypy, it would still give some guarantees about their internal correctness and the interactions between them.

**Comment by pipermerriam** [comment]
It still doesn't sit well with me to disable assertions for performance gains.

**Comment by pacrob** [comment]
Closing as not planned, looks like the performance issues are with a different lib. Please open an issue there if it's still a problem.
