### ISSUE TITLE
eth-hash dependency on eth-utils causes a circular dependency.

### ISSUE THREAD

**Issue by ilyalesokhin-starkware** [ethereum/eth-hash#32]
eth-hash dependency on eth-utils causes a circular dependency.
As a result, eth-hash cannot be used with Bazel.

When trying to install eth_hash bazel prints the following error message:
    @reqs//pypi__web3:pypi__web3
.-> @reqs//pypi__eth_utils:pypi__eth_utils
|   @reqs//pypi__eth_hash:pypi__eth_hash
`-- @reqs//pypi__eth_utils:pypi__eth_utils
This cycle occurred because of a configuration option
 
skimming over the code it does not seem like eth-utils is a real dependency.
Is it possible to remove said dependency?

**Comment by carver** [comment]
Hm, interesting. Thanks for the report, and for digging into it!

Yeah, removing it seems like the right choice. Are you interested submitting the PR?

**Comment by ilyalesokhin-starkware** [comment]
I've opened a PR.
Can you comment if anything else needs to be done?
eth-utils is mentioned in some documentation but I didn't find any actual usage.

**Comment by carver** [comment]
Just found that this was accidentally introduced in #29 .

The fix is released as v0.3.2.
