### ISSUE TITLE
Remove pysha3 as an option

### ISSUE THREAD

**Issue by carver** [ethereum/eth-hash#44]
pysha3 is no longer maintained: https://github.com/tiran/pysha3/issues/17#issuecomment-1298422777

Remove it as an option. Use hashlib as the default option if neither pycryptodome nor pysha3 are installed

Requires a major version bump. Maybe it's time to go to v1?

**Comment by kclowes** [comment]
Unfortunately, hashlib doesn't have `keccak` implemented at this point.

**Comment by kclowes** [comment]
So we may just have to have `pycryptodome` be the backend? Do you see any other options @carver?

**Comment by carver** [comment]
> So we may just have to have `pycryptodome` be the backend? Do you see any other options @carver?

Oof, not really, besides importing the source of pysha3 and taking over maintenance, which is probably not realistic :/

**Comment by Uxio0** [comment]
You can use: https://pypi.org/project/safe-pysha3/ . I updated the breaking C code, so now it's not compatible with Python < 3.9 , but we can use previous `pysha3` version for that

**Comment by kclowes** [comment]
Closed via #45. Thanks @Uxio0!
